### ISSUE TITLE
Checking/Optimizing Horovod implementation collectives

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/mesh#2]
We currently have prototypes for most of the collectives needed for actual computations in the horovod mesh implementation here:
https://github.com/DifferentiableUniverseInitiative/mesh/blob/70a13d38c5b4b16200dcb8f3d68f866633875181/mesh_tensorflow/hvd_simd_mesh_impl.py

In particular:
 - https://github.com/DifferentiableUniverseInitiative/mesh/blob/70a13d38c5b4b16200dcb8f3d68f866633875181/mesh_tensorflow/hvd_simd_mesh_impl.py#L270
 - https://github.com/DifferentiableUniverseInitiative/mesh/blob/70a13d38c5b4b16200dcb8f3d68f866633875181/mesh_tensorflow/hvd_simd_mesh_impl.py#L308
 - https://github.com/DifferentiableUniverseInitiative/mesh/blob/70a13d38c5b4b16200dcb8f3d68f866633875181/mesh_tensorflow/hvd_simd_mesh_impl.py#L378

We have detected that in some situations, depending on the mesh, the result of the computation is not quite right. This is probably due to wrong assumptions of how to split tensors and shuffle dimensions around, probably in the all2all step, maybe in the allconcat.

In particular, we found that for meshes of size 2x2 it seemed ok, but failed on 4x4.

To check these things, a good way is to start from a very simple mesh script:  https://github.com/DifferentiableUniverseInitiative/mesh/blob/hvd/examples/test_horovod.py

This script can be modified for instance to do a forward and backward FFT (taking inspiration from https://github.com/DifferentiableUniverseInitiative/IDRIS-hackathon/blob/main/scripts/fft_benchmark.py)

The steps would be:
  - [x] Add a 3D FFT and output an image that shows the residuals between inputs and outputs
  - [x] Test that script under different 2D mesh sizes, from [1x1, 2x2, 4x4] and see if a problem appears
  - [x] Given a failing configuration, try to see which `mesh_impl` functions are called, and try to narrow down which one is the culprit
  - [x] fix
  - [x] profit!

**Comment by b-remy** [comment]
Hi @EiffL , @tobias-liaudat :)

I first tried to run the scripts as there are, the [`fft_benchmark.job`](https://github.com/DifferentiableUniverseInitiative/IDRIS-hackathon/blob/main/scripts/fft_benchmark.py) scripts from the `IDRIS-hackathon` repo works properly.

However, the [`test_horovod.py`](https://github.com/DifferentiableUniverseInitiative/mesh/blob/hvd/examples/test_horovod.py) breaks with the following error:

```
--------------------------------------------------------------------------
2021-05-17 11:59:13.638743: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
WARNING:tensorflow:From /gpfslocalsup/pub/anaconda-py3/2020.02/envs/tensorflow-gpu-2.4.1+nccl-2.8.3-1/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "test_horovod.py", line 30, in <module>
    mtf.convert_to_layout_rules(layout_rules))
  File "/gpfsdswork/projects/rech/xdy/utb76xl/repo/mesh/mesh_tensorflow/hvd_simd_mesh_impl.py", line 50, in __init__
    comms, comms_id = self._create_communicators(shape)
  File "/gpfsdswork/projects/rech/xdy/utb76xl/repo/mesh/mesh_tensorflow/hvd_simd_mesh_impl.py", line 66, in _create_communicators
    periods=[False]*len(dims))
  File "mpi4py/MPI/Comm.pyx", line 1319, in mpi4py.MPI.Intracomm.Create_cart
mpi4py.MPI.Exception: MPI_ERR_ARG: invalid argument of some other kind
```

I suspect it comes from the script itself because the lines where the error come form are also used in the `fft_benchmark.job` that is working well...

Maybe it's a question of which gpu we distribute on the mesh...

One thing I could do is to start from the `fft_benchmark.py` file by making simpler operations.

**Comment by b-remy** [comment]
Or maybe it's a question of GPU allocation I used the following command on Jean Zay:
```bash
salloc --nodes=1 --ntasks-per-node=4 --cpus-per-task=10 --gres=gpu:4 --hint=nomultithread --reservation=hackathon_idr17 -A ftb@gpu
```

**Comment by b-remy** [comment]
So `test_horovod.py` works when using a slurm script. This one for instance:
```bash
#!/bin/bash
#SBATCH --job-name=test_horovod      # nom du job
##SBATCH --partition=gpu_p2          # de-commente pour la partition gpu_p2
#SBATCH --ntasks=8                   # nombre total de tache MPI (= nombre total de GPU)
#SBATCH --ntasks-per-node=4          # nombre de tache MPI par noeud (= nombre de GPU par noeud)
#SBATCH --gres=gpu:4                 # nombre de GPU par nœud (max 8 avec gpu_p2)
#SBATCH --cpus-per-task=10           # nombre de coeurs CPU par tache (un quart du noeud ici)
##SBATCH --cpus-per-task=3           # nombre de coeurs CPU par tache (pour gpu_p2 : 1/8 du noeud)
# /!\ Attention, "multithread" fait reference a l'hyperthreading dans la terminologie Slurm
#SBATCH --hint=nomultithread         # hyperthreading desactive
#SBATCH --time=00:10:00              # temps d'execution maximum demande (HH:MM:SS)
#SBATCH --output=test_horovod%j.out  # nom du fichier de sortie
#SBATCH --error=test_horovod%j.err   # nom du fichier d'erreur (ici commun avec la sortie)
#SBATCH -A ftb@gpu                   # specify the project
#SBATCH --qos=qos_gpu-dev            # using the dev queue, as this is only for profiling

# nettoyage des modules charges en interactif et herites par defaut
module purge

# chargement des modules
module load tensorflow-gpu/py3/2.4.1+nccl-2.8.3-1

# echo des commandes lancees
set -x

srun --unbuffered --mpi=pmi2 python -u test_horovod.py
```

Maybe it is because I specify there the mpi version in the line `srun --unbuffered --mpi=pmi2 /gpfslocalsup/pub/idrtools/bind_gpu.sh python -u test_horovod.py`.

@EiffL do yo know if we can do the equivalent by requiring interactive job?

Edit: it's very important to not forget to write `/gpfslocalsup/pub/idrtools/bind_gpu.sh` in the srun command (so that each process uses one GPU)

**Comment by EiffL** [comment]
yeah, so, in any case, when you run an interactive session with salloc, you then use srun to start the multiple processes.

**Comment by EiffL** [comment]
It looks like all of these things are mostly fixed in the max_hvd branch, right?

**Comment by tobias-liaudat** [comment]
It seems so

**Comment by EiffL** [comment]
ok cool, so let's close that
