### ISSUE TITLE
bug with mft.reshape

### ISSUE THREAD

**Issue by b-remy** [DifferentiableUniverseInitiative/mesh#4]
Working on #2 I implemented a script that performs a forward and inverse 3D FFT ([script](https://github.com/DifferentiableUniverseInitiative/mesh/blob/ben/examples/fft_test_horovod.py) and [job](https://github.com/DifferentiableUniverseInitiative/mesh/blob/ben/examples/script.job)).

When the computation is distributed on several GPUs, a `reshape` is required. Otherwise, only a slice of the mesh is returned. For instance, given a cube of size `128x128x128` and a `4x4` mesh on which I would distribute the x and y axes, `lowering.export_to_tf_tensor(output_field)` would return a cube of size `32x32x128`.

However, once I added the `reshape` as: https://github.com/DifferentiableUniverseInitiative/mesh/blob/64f315412abc44c811737d1a612285d712adb5a9/examples/fft_test_horovod.py#L90

so that each process get the full cube, sometimes the script seems to be stucked in the tf session...

With @EiffL , we tried to debug it and managed to enable the full computation, but only for a mesh distributed on the same node. @EiffL thought of deadlocks, so we basically added `hvd.join()` at the end of collectives function of [mesh_nbody_benchmark.py](https://github.com/DifferentiableUniverseInitiative/mesh/blob/ben/mesh_tensorflow/hvd_simd_mesh_impl.py), such as `all2all`, `allconcat` and `shift_by_n_processors`.

We still don't know how to solve the problem... In order to know if the problem comes from the mesh or the horovod layer, I'll try to reproduce the error with a script containing only reshapes and see what's happening.

**Comment by EiffL** [comment]
Hey @b-remy, I opened a new branch based on a different version of horovod, and so far it looks like I'm not getting deadlocks.... but this different horovod impl needs a bit more testing. 

Can you work on the transpose issues even with this bug and deadlocks happening? Or do we need to solve the deadlocks first?

**Comment by b-remy** [comment]
On a simpler example `mtf.transpose` also has an issue:

Comparing `tf.transpose`and `mtf.transpose` on a 4x1 mesh:
![random-4-1v2](https://user-images.githubusercontent.com/30293694/119631366-1ec65280-be10-11eb-9f5e-03c088874538.png)

There is no deadlock for this one, but we can clearly see that the transpose is correct only on one slice of the cube.

The functions from `hvd_simd_mesh_impl.py ` that `mtf.transpose` calls are: `allconcat` and `slicewise` and `slice`.

**Comment by EiffL** [comment]
so, @b-remy I think this solved itself for some reason when switching to max_vd, right? can we close it?

**Comment by b-remy** [comment]
Yes we can close it :)
It was indeed solved when using the new version of horovod and switching to the max_hvd branch.
